name: spark_mini
description: Spark Mini

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  http: ^0.13.0
  desktop_window: ^0.4.0
  # msix: ^0.1.18
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.4
  provider: ^6.0.2
  flutter_map: ^3.0.0
  searchfield: ^0.7.0
  json_annotation: ^4.4.0
  # flutter_file_manager:
  # permission_handler:
  # path_provider: ^2.0.3
  # open_file: ^3.2.1
  share_plus: ^4.0.8
  intl:
  archive:
  flutter_riverpod: ^2.0.1
  # esys_flutter_share:
  #   git:
  #     url: git://github.com/jawad12345A/esys-flutter-share.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  percent_indicator: "^4.0.0"
  network_info_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^2.2.10+1
  # msix: ^0.1.5
  build_runner:
  json_serializable: ^6.4.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ignite_logo.png"
  image_path_ios: "assets/icon/ignite_logo_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
    # - assets/rec_2020-07-31_23-30-41.echoreplay
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
msix_config:
  display_name: Spark Mini
  publisher_display_name: ignitevr.gg
  publisher:
  identity_name:
  msix_version: 1.0.0.0
  icons_background_color: "#ffffff"
  architecture: x64
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient"
