name: spark_mini
version: 1.0.0
summary: Spark Mini
description: Non-Windows version of Spark (formerly IgniteBot)

confinement: strict
base: core18
grade: stable

slots:
  dbus-spark_mini: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: gg.ignitevr.spark_mini # adjust accordingly to your app name and
    
apps:
  spark_mini:
    command: spark_mini
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-spark_mini
parts:
  spark_mini:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
