name: spark-mini
version: 1.0.4
summary: Spark Mini
description: Non-Windows version of Spark (formerly IgniteBot)

confinement: strict
base: core18
grade: stable

# slots:
#   dbus-spark-mini: # adjust accordingly to your app name
#     interface: dbus
#     bus: session
#     name: gg.ignitevr.spark-mini # adjust accordingly to your app name and
    
apps:
  spark-mini:
    command: spark_mini
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-spark-mini
parts:
  spark-mini:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
